name: Initialization action
description: Common actions to initialize a Job

inputs:
  thunderstore-client:
    description: True if the Thunderstore client should be installed
    required: false

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.405

    - name: Restore project dependencies
      shell: bash
      run: dotnet restore

    - name: Install NetcodePatcher
      shell: bash
      run: dotnet tool install -g evaisa.netcodepatcher.cli

    - name: Install Thunderstore client
      if: ${{ inputs.thunderstore-client == 'true' }}
      shell: bash
      # https://github.com/thunderstore-io/thunderstore-cli
      run: dotnet tool install -g tcli
    
    - name: Add NuGet Package Source GitHub
      shell: bash
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
